name: ci

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  cd:
    uses: oncoursesystems/workflows/.github/workflows/web-ci.yml@main
    secrets: inherit
