name: pr-preview-cleanup

on:
  pull_request:
    types: [closed, unlabeled]

env:
  PREVIEW_LABEL: preview

jobs:
  cleanup-image:
    if: ${{ github.event.label.name == env.PREVIEW_LABEL }}
    runs-on: linux
    steps:
      - name: Delete Docker image
        uses: bots-house/ghcr-delete-image-action@v1.1.0
        with:
          owner: oncoursesystems
          name: ${{ github.repository }}
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: pr-${{ github.event.pull_request.number }}

  cleanup-charts:
    if: ${{ github.event.label.name == env.PREVIEW_LABEL }}
    strategy:
      matrix:
        env: [devel, staging]
    uses: oncoursesystems/workflows/.github/workflows/pr-preview-cleanup.yml@main
    secrets: inherit
    with:
      runs-on: linux
      deployment-name: oncourse-systems-${{ matrix.env }}

  remove-comment:
    if: ${{ github.event.label.name == env.PREVIEW_LABEL }}
    runs-on: linux
    steps:
      - name: Find comment
        uses: peter-evans/find-comment@v3
        id: fc
        with:
          issue-number: ${{ github.event.pull_request.number }}
          comment-author: github-actions[bot]
          body-includes: pull request preview
      - name: Delete comment
        uses: sandeshjangam/comment-actions@v1
        if: ${{ steps.fc.outputs.comment-id != ''}}
        with:
          type: delete
          comment_id: ${{ steps.fc.outputs.comment-id }}
