name: pr-preview-deploy

on:
  pull_request:
    types: [labeled]

jobs:
  docker-build:
    uses: oncoursesystems/workflows/.github/workflows/docker-build.yml@main
    secrets: inherit
    with:
      runs-on: ${{ inputs.runs-on }}

  cd:
    needs: docker-build
    uses: oncoursesystems/workflows/.github/workflows/pr-preview-deploy.yml@main
    secrets: inherit
    with:
      base-url: preview.oncoursesystems.com
      values-yaml: ./github/workflows/pr-preview-values.yaml
