name: pr-preview-cleanup

on:
  pull_request:
    types: [closed, unlabeled]

jobs:
  cleanup-pr:
    uses: oncoursesystems/workflows/.github/workflows/pr-preview-cleanup.yml@main
    secrets: inherit
