on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  cd:
    uses: oncoursesystems/reusable-workflows/.github/workflows/mobile-ci@master
    secrets: inherit