name: cleanup

on:
  pull_request:
    types: [closed]

jobs:
  clean:
    uses: oncoursesystems/workflows/.github/workflows/expo-eas-cleanup.yml@main
    with:
      channel: ${{ format('pr-{0}', github.event.number) }}
      runs-on: self-hosted