name: docker-cleanup

on:
  workflow_call:
    inputs:
      runs-on:
        type: string
        default: self-hosted
      package-name:
        type: string
        default: ${{ github.repository }}

jobs:
  release:
    runs-on: ${{ inputs.runs-on }}
    steps:
      - name: Delete untagged packages
        uses: actions/delete-package-versions@v5
        with:
          package-name: ${{ inputs.package-name }}
          package-type: "container"
          delete-only-untagged-versions: true
