name: mobile-cd

on:
  workflow_call:
    inputs:
      runs-on:
        type: string
        default: arc-kubernetes-cluster

jobs:
  eas-update:
    uses: ./.github/workflows/expo-eas-update.yml
    with:
      channel: production
      message: ${{ github.event.release.tag_name }}
      runs-on: ${{ inputs.runs-on }}
    secrets:
      expo-token: ${{ secrets.EXPO_TOKEN }}

  submit-ios:
    uses: ./.github/workflows/expo-eas-submit.yml
    with:
      platform: "ios"
      runs-on: ${{ inputs.runs-on }}
    secrets:
      expo-token: ${{ secrets.EXPO_TOKEN }}

  submit-android:
    uses: ./.github/workflows/expo-eas-submit.yml
    with:
      platform: "android"
      runs-on: ${{ inputs.runs-on }}
    secrets:
      expo-token: ${{ secrets.EXPO_TOKEN }}
