name: pr-preview-cleanup

on:
  workflow_call:
    inputs:
      runs-on:
        description: Defines the type of machine to run the workflow on
        type: string
        required: false
        default: self-hosted
      deployment-name:
        description: The name of the helm chart deployment
        type: string
        required: false
        default: pr-preview
      namespace:
        description: The namespace to install the helm chart
        type: string
        required: false
        default: pr-preview
      image-name:
        description: The docker image name
        type: string
        required: false
        default: ${{ github.repository }}

jobs:
  cleanup:
    runs-on: ${{ inputs.runs-on }}
    steps:
      - name: Delete Docker package
        uses: bots-house/ghcr-delete-image-action@v1.1.0
        with:
          owner: oncoursesystems
          name: ${{ image-name }}
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: pr-${{ github.event.pull_request.number }}

      - name: Delete Helm chart
        uses: wahyd4/kubectl-helm-action@master
        env:
          KUBE_CONFIG_DATA: ${{ secrets.KUBECONFIG }}
        with:
          args: |
            helm delete ${{ inputs.deployment-name }}-${{ github.event.pull_request.number }} --namespace ${{ inputs.namespace }}
