name: pr-preview-cleanup

on:
  workflow_call:
    inputs:
      runs-on:
        type: string
        default: self-hosted
      namespace:
        type: string
        default: pr-preview

jobs:
  cleanup:
    runs-on: ${{ inputs.runs-on }}
    steps:
      - name: Delete Helm chart
        uses: wahyd4/kubectl-helm-action@master
        env:
          KUBE_CONFIG_DATA: ${{ secrets.KUBECONFIG }}
        with:
          args: |
            helm delete pr-preview-${{ github.event.pull_request.number }} --namespace ${{ inputs.namespace }}
