name: pr-preview-deploy

on:
  workflow_call:
    inputs:
      runs-on:
        type: string
        default: self-hosted
      base-url:
        type: string
        required: true
      chart-repository:
        type: string
        default: https://bjw-s.github.io/helm-charts
      chart-name:
        type: string
        default: app-template
      chart-version:
        type: string
        default: 2.6.0
      namespace:
        type: string
        default: pr-preview
      values-yaml:
        type: string
        required: true
      deployment-name:
        type: string
        default: pr-preview

jobs:
  install-chart:
    runs-on: ${{ inputs.runs-on }}
    steps:
      - name: Checkout yaml file
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            ${{ inputs.values-yaml }}
          sparse-checkout-cone-mode: false
      - name: Install Helm chart
        uses: wahyd4/kubectl-helm-action@master
        env:
          KUBE_CONFIG_DATA: ${{ secrets.KUBECONFIG }}
        with:
          args: |
            helm repo add pr-preview ${{ inputs.chart-repository }}
            helm upgrade ${{ inputs.deployment-name }}-pr${{ github.event.pull_request.number }} pr-preview/${{ inputs.chart-name }} \
              --install \
              --namespace ${{ inputs.namespace }} \
              --create-namespace \
              --version ${{ inputs.chart-version }} \
              --wait \
              --values ${{ inputs.values-yaml }} \
              --set controllers.main.containers.main.image.tag=pr-${{ github.event.pull_request.number }} \
              --set ingress.main.hosts[0].host=pr-${{ github.event.pull_request.number }}.${{ inputs.base-url }} \
              --set ingress.main.tls[0].hosts[0]=pr-${{ github.event.pull_request.number }}.${{ inputs.base-url }}
