name: pr-preview-cleanup

on:
  workflow_call:
    inputs:
      runs-on:
        description: Defines the type of machine to run the workflow on
        type: string
        required: false
        default: self-hosted
      base-url:
        type: string
        required: true
      deployment-name:
        description: The name of the helm chart deployment
        type: string
        required: false
        default: pr-preview
      namespace:
        description: The namespace to install the helm chart
        type: string
        required: false
        default: pr-preview
      image-name:
        description: The docker image name
        type: string
        required: false
        default: ${{ github.repository }}

jobs:
  cleanup:
    runs-on: ${{ inputs.runs-on }}
    steps:
      - name: Delete Helm chart
        uses: wahyd4/kubectl-helm-action@master
        env:
          KUBE_CONFIG_DATA: ${{ secrets.KUBECONFIG }}
        with:
          args: |
            helm delete ${{ inputs.deployment-name }}-${{ github.event.pull_request.number }} --namespace ${{ inputs.namespace }}
      - name: Find comment
        uses: peter-evans/find-comment@v3
        id: fc
        with:
          issue-number: ${{ github.event.number }}
          comment-author: github-actions[bot]
          body-includes: https://pr-${{ github.event.pull_request.number }}.${{ inputs.base-url }}
      - name: Delete comment
        uses: detomarco/delete-comment@v1
        with:
          comment-id: ${{ steps.fc.outputs.comment-id }}
