name: web-cd

on:
  workflow_call:
    inputs:
      runs-on:
        type: string
        default: self-hosted

jobs:
  docker-publish:
    uses: ./.github/workflows/docker-build.yml
    with:
      runs-on: ${{ inputs.runs-on }}
